# Generated by Django 5.1.6 on 2025-05-26 22:07

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0002_logdesistema'),
    ]

    operations = [
    ]
