# Generated by Django 5.1.6 on 2025-05-26 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0003_auto_20250526_1907'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='logdesistema',
            options={'verbose_name': 'Log de Sistema', 'verbose_name_plural': 'Logs de Sistema'},
        ),
        #migrations.AddField(
        #    model_name='documento',
        #    name='usuario',
        #   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to=settings.AUTH_USER_MODEL),
        #),
        migrations.AddField(
            model_name='logdesistema',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='analise.categoria'),
        ),
        migrations.AlterField(
            model_name='logdesistema',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='analise.documento'),
        ),
    ]
